### ISSUE TITLE
Stumbling upon here: What sense does this repo make?

### ISSUE THREAD

**Issue by TimSusa** [ianstormtaylor/to-snake-case#3]
Hi, 

sry to come arround the corner here, but in you package.json you have:

``` 
  "dependencies": {
    "to-space-case": "^1.0.0"
  },
```

which is just providing the main functionality for your repo here, as it seems to me. So why you are creating a further connection with your repo, which is just using the 3rd party lib not more? You could just use the 3rd party lib directly and pin this version fixed in package.json instead. The other way arround, if the case occurs, your lib is not available anymore, this repo here aswell will fail do work. So IMO this is completely overhead in my opinion.

**Comment by ianstormtaylor** [comment]
Hey @TimSusa I’m sure not I follow all that. But in case it helps, that “3rd-party” lib is also mine. 

But if you’re wondering why it’s not all in one library with exports, or all in a monorepo, it’s because this was made ~5 years ago, before the tooling was good enough to make those choices work well.

**Comment by TimSusa** [comment]
Ah okay, I see. Sry! No worries. Thanks for giving Feedback! In my company we use slatejs for years now. My ex team might be really excited to get in touch with you for questions and answers. Please reach out to me if you are interested as my company would might be ok to pay efforts for you.
